import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        outline: "#767587",
        "surface-variant": "#e0e3e5",
        "on-secondary": "#ffffff",
        "surface-container": "#eceef0",
        "on-surface": "#191c1e",
        background: "#f7f9fb",
        "on-secondary-fixed": "#09006b",
        secondary: "#413de4",
        "on-primary-fixed-variant": "#004f58",
        "on-tertiary": "#ffffff",
        "on-secondary-container": "#fbf7ff",
        "on-tertiary-container": "#fff8fd",
        "surface-container-high": "#e6e8ea",
        tertiary: "#8025ce",
        "tertiary-fixed-dim": "#ddb7ff",
        error: "#ba1a1a",
        "on-primary": "#ffffff",
        "inverse-primary": "#00daf3",
        "on-primary-container": "#f1fdff",
        "on-tertiary-fixed-variant": "#6900b3",
        "primary-fixed-dim": "#00daf3",
        "primary-fixed": "#9cf0ff",
        "on-error": "#ffffff",
        "inverse-on-surface": "#eff1f3",
        "surface-container-low": "#f2f4f6",
        "on-primary-fixed": "#001f24",
        "primary-container": "#007f8e",
        "surface-tint": "#006875",
        "outline-variant": "#c7c4d8",
        "secondary-container": "#5c5bfe",
        "secondary-fixed-dim": "#c1c1ff",
        "on-surface-variant": "#464556",
        "on-error-container": "#93000a",
        primary: "#006471",
        surface: "#f7f9fb",
        "inverse-surface": "#2d3133",
        "on-secondary-fixed-variant": "#2b20d2",
        "surface-container-highest": "#e0e3e5",
        "error-container": "#ffdad6",
        "tertiary-container": "#9a46e9",
        "on-tertiary-fixed": "#2c0051",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed": "#f0dbff",
        "on-background": "#191c1e",
        "surface-dim": "#d8dadc",
        "surface-bright": "#f7f9fb",
        "secondary-fixed": "#e1dfff",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        headline: ["Space Grotesk", "sans-serif"],
        body: ["Manrope", "sans-serif"],
        label: ["Space Grotesk", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
    },
  },
  plugins: [],
};

export default config;
